vpc_cidr_block = "10.0.0.0/16"
subnet_cidr_block = "10.0.10.0/24"
avai_zone = "ap-south-1b"
env_prifix = "dev"
instance_type = "t2.micro"
public_key_location = "/home/sweethome/.ssh/id_rsa.pub"
image_name = "amzn2-ami-hvm-*-x86_64-gp2"
